# Generated by Django 2.1.1 on 2018-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
    ]
