# Generated by Django 2.1.1 on 2018-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='survey',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
